<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>RIoT2.Matter.ControlBridge</RootNamespace>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <Version>0.1.13</Version>
        <RIoT2MatterPackageVersion Condition="'$(RIoT2MatterPackageVersion)' == ''">0.1.13</RIoT2MatterPackageVersion>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="RIoT2.Matter" Version="$(RIoT2MatterPackageVersion)" />
    </ItemGroup>

</Project>