using RIoT2.Matter.DataModel;
using RIoT2.Matter.InteractionModel;

namespace RIoT2.Matter.Device;

/// <summary>
/// An event generated by a cluster and retained by the <see cref="EventManager"/>: its node-wide
/// number, source path, priority, generation time, and opaque TLV payload. Projected to an
/// <see cref="EventDataIB"/> when reported. See the Matter Core Specification, section 8.9.
/// </summary>
public sealed record GeneratedEvent
{
    /// <summary>The monotonically increasing node-wide event number.</summary>
    public required ulong EventNumber { get; init; }

    /// <summary>The endpoint that generated the event.</summary>
    public required EndpointId Endpoint { get; init; }

    /// <summary>The cluster that generated the event.</summary>
    public required ClusterId Cluster { get; init; }

    /// <summary>The event identifier within the cluster.</summary>
    public required EventId Event { get; init; }

    /// <summary>The event's priority level.</summary>
    public required EventPriority Priority { get; init; }

    /// <summary>POSIX-epoch generation time in milliseconds.</summary>
    public required ulong EpochTimestampMs { get; init; }

    /// <summary>The event payload as a standalone TLV element (TlvCopier.Capture form).</summary>
    public required ReadOnlyMemory<byte> Payload { get; init; }

    /// <summary>Projects this event to its <see cref="EventDataIB"/> wire form (absolute timestamp).</summary>
    public EventDataIB ToEventData() => new()
    {
        Path = new EventPathIB { Endpoint = Endpoint, Cluster = Cluster, Event = Event },
        EventNumber = EventNumber,
        Priority = Priority,
        EpochTimestamp = EpochTimestampMs,
        Data = Payload,
    };
}