using RIoT2.Matter.DataModel;
using RIoT2.Matter.InteractionModel;

namespace RIoT2.Matter.Device;

/// <summary>
/// Receives events generated by clusters, assigning each a node-wide event number and retaining it
/// for later reporting. Implemented by the node's <see cref="EventManager"/>. See the Matter Core
/// Specification, section 8.9 (Events).
/// </summary>
public interface IEventSink
{
    /// <summary>
    /// Records a generated event and returns its allocated, monotonically increasing node-wide
    /// event number. <paramref name="payload"/> is a standalone TLV element (TlvCopier.Capture form).
    /// </summary>
    ulong Record(EndpointId endpoint, ClusterId cluster, EventId eventId, EventPriority priority, ReadOnlyMemory<byte> payload);

    /// <summary>Records an event with fabric ownership; custom sinks must retain that ownership.</summary>
    ulong Record(EndpointId endpoint, ClusterId cluster, EventId eventId, EventPriority priority,
        ReadOnlyMemory<byte> payload, FabricIndex? fabricIndex)
    {
        if (fabricIndex is not null) { throw new NotSupportedException("This event sink does not preserve fabric ownership."); }
        return Record(endpoint, cluster, eventId, priority, payload);
    }
}